name: Build

on: [push]

jobs:
  linux-build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      
    - name: Create Gradle Build
      run: gradle build
      
  macOS-build:
    
    runs-on: macOS-latest
    
    steps:
      - uses: actions/checkout@v1
        
      - name: Create Gradle Build
        run: gradle build

      
