name: Build

on: [push]

jobs:
  linux-build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      
    - name: Create Gradle Build
      run: gradle :assemble :linuxMainKlibrary
      
    - uses: actions/upload-artifact@master
      with:
        name: my-artifact
        path: build/classes/kotlin/linux/main/kotlin-io.klib
      
      
  macOS-build:
    
    runs-on: macOS-latest
    
    steps:
      - uses: actions/checkout@v1
        
      - name: Create Gradle Build
        run: gradle build

      
