name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: docker://gcr.io/cloud-builders/gradle
      
    - name: Gradle Build...
      run: gradle build
      
